import styles from "./admin.module.scss";
import { Suspense } from "react";
import { auth } from "@/lib/auth";
import AdminPosts from "@/components/admin/adminPosts";
import AdminPostForm from "@/components/admin/adminPostForm";
import AdminUsers from "@/components/admin/adminUsers";
import AdminUserForm from "@/components/admin/adminUserForm";
import AdminCharacters from "@/components/admin/adminCharacters";
import AdminCharForm from "@/components/admin/adminCharForm";

const AdminPage = async () => {
  const session = await auth();

  return (
    <>
      <h1 className={styles.headline}>Dev Admin</h1>

      <div className={styles.devNotes}>
        <p>
          This is a <b>dev tool</b> used to test database behaviour.
        </p>

        <h3>Future plans:</h3>

        <p>
          This should either only exist in the production environment in
          it&apos;s current form - or it could be refactored and repurposed as
          an <i>admin dashboard</i> for PD administators.
        </p>
      </div>

      <div className={styles.container}>
        <Suspense fallback={<div>Loading...</div>}>
          <AdminUserForm />
        </Suspense>

        <Suspense fallback={<div>Loading...</div>}>
          <AdminUsers />
        </Suspense>

        <Suspense fallback={<div>Loading...</div>}>
          <AdminCharForm />
        </Suspense>

        <Suspense fallback={<div>Loading...</div>}>
          <AdminCharacters />
        </Suspense>

        <Suspense fallback={<div>Loading...</div>}>
          <AdminPostForm />
        </Suspense>

        <Suspense fallback={<div>Loading...</div>}>
          <AdminPosts />
        </Suspense>
      </div>
    </>
  );
};

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default AdminPage;
